/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kalkulator;

/**
 *
 * @author Fariz
 */
public class KalkulatorView extends javax.swing.JFrame {

    /**
     * Creates new form KalkulatorView
     */
    public KalkulatorView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        btn9 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        btnEqual = new javax.swing.JButton();
        btnBagi = new javax.swing.JButton();
        btnKali = new javax.swing.JButton();
        btnKurang = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jTextField1);
        jTextField1.setBounds(10, 11, 380, 60);

        btn9.setText("9");
        getContentPane().add(btn9);
        btn9.setBounds(170, 90, 39, 50);

        btn7.setText("7");
        getContentPane().add(btn7);
        btn7.setBounds(10, 90, 39, 50);

        btn8.setText("8");
        getContentPane().add(btn8);
        btn8.setBounds(90, 90, 39, 50);

        btn4.setText("4");
        getContentPane().add(btn4);
        btn4.setBounds(10, 150, 39, 50);

        btn5.setText("5");
        getContentPane().add(btn5);
        btn5.setBounds(90, 150, 39, 50);

        btn6.setText("6");
        getContentPane().add(btn6);
        btn6.setBounds(170, 150, 39, 50);

        btn1.setText("1");
        getContentPane().add(btn1);
        btn1.setBounds(10, 210, 39, 50);

        btn2.setText("2");
        getContentPane().add(btn2);
        btn2.setBounds(90, 210, 39, 50);

        btn3.setText("3");
        getContentPane().add(btn3);
        btn3.setBounds(170, 210, 39, 50);

        btn0.setText("0");
        getContentPane().add(btn0);
        btn0.setBounds(10, 270, 39, 50);

        jButton11.setText(",");
        getContentPane().add(jButton11);
        jButton11.setBounds(90, 270, 37, 50);

        btnEqual.setText("=");
        getContentPane().add(btnEqual);
        btnEqual.setBounds(170, 270, 41, 50);

        btnBagi.setText("/");
        getContentPane().add(btnBagi);
        btnBagi.setBounds(250, 270, 37, 50);

        btnKali.setText("x");
        getContentPane().add(btnKali);
        btnKali.setBounds(250, 210, 39, 50);

        btnKurang.setText("-");
        getContentPane().add(btnKurang);
        btnKurang.setBounds(250, 150, 37, 50);

        btnTambah.setText("+");
        getContentPane().add(btnTambah);
        btnTambah.setBounds(250, 90, 41, 50);

        btnClear.setText("C");
        getContentPane().add(btnClear);
        btnClear.setBounds(330, 270, 39, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KalkulatorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KalkulatorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KalkulatorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KalkulatorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KalkulatorView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnBagi;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEqual;
    private javax.swing.JButton btnKali;
    private javax.swing.JButton btnKurang;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton jButton11;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
